### Numpy 배열의 연산

#### 리스트 연산과 Numpy 배열의 연산 비교:

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
a + a # 반복

[1, 2, 3, 1, 2, 3]

In [4]:
a*3 # 반복

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
b = np.array([1, 2, 3])

In [6]:
b*3 # 원소 연산

array([3, 6, 9])

In [7]:
b + b # 원소 연산

array([2, 4, 6])

In [8]:
np.repeat(b, 3) # 원소마다 반복

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [9]:
np.tile(b, 3) # 원소 순서대로 반복

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

#### Numpy 배열의 연산:

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [11]:
a+b

array([5, 7, 9])

In [12]:
a-b

array([-3, -3, -3])

In [13]:
a*b

array([ 4, 10, 18])

In [14]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 연산의 벡터화 (universal function):

In [15]:
x = np.array([0, 1, 2, 3, 4, 5])

In [16]:
pow(10, x) # 10^x제곱

array([     1,     10,    100,   1000,  10000, 100000], dtype=int32)

In [17]:
x**3 # ^3

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [18]:
np.sqrt(x) # 제곱근

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [19]:
np.exp(x) # e^x제곱

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [20]:
np.cumsum(x) # 누적합

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

#### Numpy가 제공하는 함수:

In [21]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [22]:
np.unique(a) # 중복 제거(=set)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.median(a) # 중앙값

5.0

In [24]:
np.sum(a) # 합

5485

In [25]:
np.round(np.var(a),2) # 분산, 둘째 자리 반올림

8.19

In [26]:
np.round(np.mean(a),2) # 평균

5.48

In [27]:
np.round(np.std(a),2) # 표준편차

2.86

In [28]:
np.max(a)

10

In [29]:
np.min(a)

1

#### 배열의 메서드로 제공되는 함수:

In [30]:
x = np.arange(1,11)

In [31]:
x.sum()

55

In [32]:
x.mean()

5.5

In [33]:
x.std()

2.8722813232690143

In [34]:
x.var()

8.25

In [35]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [36]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(y.mean(axis=0)) # 열

[4. 5. 6.]


In [38]:
print(y.mean(axis=1)) # 행

[2. 5. 8.]


In [39]:
z = np.random.randint(10,size=1000)

In [40]:
z.max() # 최대

9

In [41]:
z.min() # 최소

0

In [42]:
(z > 5).sum()

392

In [43]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [46]:
a.argmax() # 최대값 위치

4

In [47]:
a.argmin() # 최소값 위치

1