### Numpy 행렬과 선형대수학

In [1]:
import numpy as np

#### 내적 구하기:

In [2]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])

In [3]:
np.dot(x,y) # 내적

44

In [4]:
x.dot(y)

44

In [5]:
np.sum(x*y)

44

#### dot 연산자:

In [6]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])
x = x.reshape((3,1))
y = y.reshape((1,3))
print("{}".format(x))
print(" ----------")
print("{}".format(y))

[[1]
 [3]
 [5]]
 ----------
[[2 4 6]]


In [7]:
y.dot(x)[0,0]

44

In [8]:
x.dot(y)

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

#### 행렬 만들기:

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.random.seed(222)
np.random.random((2,2))

array([[0.52602843, 0.68531719],
       [0.83567419, 0.65376526]])

In [12]:
np.random.seed(111)
np.random.randn(2,2)

array([[-1.13383833,  0.38431919],
       [ 1.49655378, -0.3553823 ]])

In [13]:
np.diag([1,2,3]) # 대각행렬

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### 행렬의 연산 (행렬과 행렬):

In [14]:
m1 = np.array([[1, 2, 3],[4, 5, 6]])
m2 = np.array([[6, 5, 4],[3, 2, 1]])

In [15]:
m1+m2

array([[7, 7, 7],
       [7, 7, 7]])

In [16]:
m1*m2

array([[ 6, 10, 12],
       [12, 10,  6]])

In [17]:
np.transpose(m2) # 전치행렬

array([[6, 3],
       [5, 2],
       [4, 1]])

In [18]:
np.dot(m1,np.transpose(m2))

array([[28, 10],
       [73, 28]])

#### 행렬의 연산 (행렬과 스칼라):

In [19]:
m = np.array([[1, 2],[3, 4]])

In [20]:
m*3

array([[ 3,  6],
       [ 9, 12]])

In [21]:
m/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [22]:
m+1

array([[2, 3],
       [4, 5]])

#### 역행렬:

In [23]:
m = np.array([[1, 2],[3, 4]])
minv = np.linalg.inv(m) # 역행렬
minv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
mres = np.dot(m, minv)
np.round(mres,2) 

array([[1., 0.],
       [0., 1.]])

#### 연립 방정식 (선형 방정식의 개수 = 미지수의 개수인 경우):

In [25]:
A = np.array([[5, 8],[6, 4]])
b = np.array([[30], [25]])
Ainv = np.linalg.inv(A)
print(np.dot(Ainv,b))

[[2.85714286]
 [1.96428571]]


In [26]:
np.linalg.solve(A, b) # 해 찾기

array([[2.85714286],
       [1.96428571]])